services:
  minishell:
    container_name: "minishell"
    # image: qemux/qemu-docker
    restart: always
    build:
      context: ./minishell
      dockerfile: Dockerfile

    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - FSETID
      - SETUID

    # Prevents gaining new privileges
    devices:
      - /dev/kvm
    security_opt:
      - no-new-privileges

    networks:
      website_net:
        ipv4_address: "88.88.5.2"

    expose:
      - "8006"

    # volumes:
    #   - /home/victor/git/website/minishell/linux-minishell/alpine-custom.iso:/boot.iso

    # environment:
    #     DISK_SIZE: "1GB"
    #     RAM_SIZE: "500MB"
    #     ARGUMENTS: "-boot d"
    #     DEBUG: "1"
    #     BOOT_MODE: "legacy"
        # BOOT: "https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/x86_64/alpine-virt-3.21.3-x86_64.iso"

    # networks:
    #   - website_net

  nginx:
    container_name: "nginx"
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile

    networks:
      website_net:
        ipv4_address: "88.88.5.1"

    ports:
      - "19001:80"

  website:
    container_name: "site"
    restart: always
    build:
      context: ./vvsite
      dockerfile: Dockerfile

    networks:
      website_net:
        ipv4_address: "88.88.5.3"

    expose:
      - "3000"

networks:
  website_net:
    # external: false
    # internal: true
    driver: bridge
    ipam:
      config:
        - subnet: "88.88.0.0/21"
