services:
  minishell:
    container_name: "minishell"
    # image: qemux/qemu-docker
    restart: always
    build:
      context: ./minishell
      dockerfile: Dockerfile

    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - CHOWN
      - SETGID
      - DAC_OVERRIDE
      - FSETID
      - SETUID

    # Prevents gaining new privileges
    devices:
      - /dev/kvm
      - /dev/net/tun
    security_opt:
      - no-new-privileges

    # volumes:
    #   - /home/victor/git/website/minishell/linux-minishell/alpine-custom.iso:/boot.iso

    # environment:
    #     DISK_SIZE: "1GB"
    #     RAM_SIZE: "500MB"
    #     ARGUMENTS: "-boot d"
    #     DEBUG: "1"
    #     BOOT_MODE: "legacy"
        # BOOT: "https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/x86_64/alpine-virt-3.21.3-x86_64.iso"

    # networks:
    #   - website_net
    ports:
      - "8006:8006"

networks:
  website_net:
    external: false
    internal: true
