services:
  minishell:
    container_name: "minishell"
    build:
      context: ./minishell
      dockerfile: Dockerfile

    # cap_drop:
    #   - ALL
    cap_add:
      - NET_ADMIN
      - CHOWN
      - SETGID
      - DAC_OVERRIDE
      # - FSETID
      - SETUID

    volumes:
      - /home/vvobis/sgoinfre/git/personal/website/minishell/alpine/alpine-custom.iso:/boot.iso

    # Prevents gaining new privileges
    devices:
      - /dev/kvm
      - /dev/net/tun
    security_opt:
      - no-new-privileges

    environment:
        DISK_SIZE: "1GB"
        RAM_SIZE: "500MB"

    # networks:
    #   - website_net
    ports:
      - "8006:8006"

networks:
  website_net:
    external: false
    internal: true
